[Audit policy] Support Event Hub and Log Analytics in server and database audit policy commands (#15444)
* In progress - rollback delete is missing

* Added help

* Added help

* Working on rollback

* Fix '_get_diagnostic_settings_url' for server case

* update help

* fix storage account and endpoint handling

* update test - server tests still fail with:
AssertionError: You need to call 'result' or 'wait' on all LROPoller you have created

* Add log analytics test for db audit

* use bool condition for test mode

* enrich db audit policy tests

* fix case when blob_storage_target_state is not provided

* fix diagnostic settings rollback

* Tune server and db tests.
Server tests still failed.

* Wait on LROPoller for server operations

* remove timeouts
server tests pass now

* _audit_policy_update_global_settings cosmetic

* use proper --event-hub argument name

* merge from main repository - resolve conflicts

* code style

* code style

* code style

* code style

* code style

* code style

* support --no-wait in 'server audit-policy update'

* code style check passed

* optimize if-else

* remane to 'fetch...'

* fix audit_policy_update logic in terms of azure monitor

* code style

* remove unused arguments

* linter

* use is_storage_secondary_key_in_use from audit_policy

* fix typo

* validate --retention-days argument

* fix error description

* bound retention_days from top

* fix 'has_other_categories'

* fix positional arguments comments

* reuse cf_monitor

* added 'wait' command

* fix 'wait' command help

* register 'wait' as last command

* update 'wait' help

* us 'cmd.get_models' to obtain model classes

* use 'generic_update_command' for server and db audit-policy update

* style fixes

Co-authored-by: Oleg Sternberg <olsternb@microsoft.com>