[App Service] Fix #21574: `az webapp vnet-integration add`: Fix the AttributeError that 'NoneType' object has no attribute 'server_farm_id' (#21636)
* fix webapp vnet-integration add

* remove unused import