{AzureMediaService} fixes Azure/azure-cli#23937 (#23958)
* {AzureMediaService} fixes Azure/azure-cli#23937

fixes Azure/azure-cli#23937
Looking at this test case https://github.com/phcooper/azure-cli/blob/d3cda79e4819f9008e7a8fd0b4283dc86fb0057c/src/azure-cli/azure/cli/command_modules/ams/tests/latest/test_ams_account_scenarios.py#L34 

It clearly indicates that the Resource Group and Account name both are required.

Currently the CLI command az ams account show --name <mediaservicename> throws the below error:

  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 363, in handler
    show_exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/arm.py", line 429, in show_exception_handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 361, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/ams/operations/account.py", line 17, in get_mediaservice
    account_name) if resource_group_name else client.get_by_subscription(account_name)
AttributeError: 'MediaservicesOperations' object has no attribute 'get_by_subscription'

And the az ams account show command requires both Resource Group and Account Name and the customer has shared the feedback that it shouldn't throw the error but instead give a friendly error message. This PR helps to achieve this.

* Update account.py

* Update account.py

* Update account.py

* Update account.py

* Update account.py

* Update account.py