{ServiceBus} fixes Azure/azure-cli#25161 fix for migration abort issue (#25323)
* {AzureServiceBus} fixes Azure/azure-cli#25161 fix for migration abort issue

Azure/azure-cli#25161 fix for migration abort issue

Azure CLI command `az servicebus migration abort` fails with the below error:
```
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/servicebus/v2022_01_01_preview/operations/_migration_configs_operations.py", line 766, in revert
    request = build_revert_request(
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/servicebus/v2022_01_01_preview/operations/_migration_configs_operations.py", line 251, in build_revert_request
    "configName": _SERIALIZER.url("config_name", config_name, 'str'),
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 652, in url
    output = self.serialize_data(data, data_type, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 760, in serialize_data
    raise ValueError("No value for given attribute")
ValueError: No value for given attribute
```

This is because the config-name parameter with ($defualt0 value isnt passed to the below function:

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/servicebus/azure-mgmt-servicebus/azure/mgmt/servicebus/v2022_01_01_preview/operations/_migration_configs_operations.py#L733

This PR fixes the above error by passing the config_name parameter to the revert function while performing migration abort operation.

* Update custom.py