Avoid throwing exception when updating autoscale settings with notifications set to null
Invoking the following command throws an exception, as seen below:

$ az monitor autoscale update --name autoscalewad --resource-group my-resource-group --max-count 2
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.6/dist-packages/azure/cli/core/commands/__init__.py", line 333, in execute
    cmd.exception_handler(ex)
  File "/usr/local/lib/python3.6/dist-packages/azure/cli/command_modules/monitor/_exception_handler.py", line 24, in monitor_exception_handler
    reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/azure/cli/core/commands/__init__.py", line 310, in execute
    result = cmd(params)
  File "/usr/local/lib/python3.6/dist-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/azure/cli/core/commands/arm.py", line 429, in handler
    instance = custom_function(instance=instance, **custom_func_args)
  File "/usr/local/lib/python3.6/dist-packages/azure/cli/command_modules/monitor/operations/autoscale_settings.py", line 126, in autoscale_update
    notification = next(x for x in instance.notifications if x.operation.lower() == 'scale')
TypeError: 'NoneType' object is not iterable

The reason is that the code didn't expect to see "notifications" field in autoscale settings json set to null.

This PR adds more check and simplify a little the code by adding a new notification update routine.