Fixed test failure in test_sql_db_mgmt.
The assertion error is:
JMESPathCheckAssertionError: Query '[1].name' doesn't yield expected value 'master', instead the actual value is 'cliautomationdb01'.

The fix is to sort the database names returned from the service so that it's guaranteed they are in order.